version: '3.7'

services:
  php:
    build:
      context: docker/php
    volumes:
      - ./:/srv/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  chrome:
    image: browserless/chrome
    environment:
      PREBOOT_CHROME: 'true'
      ENABLE_CORS: 'true'
