name: PantherExtension CI
on:
  push:
    branches:
      - master
jobs:
  panther_extension:
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }}
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
        composer-dependencies: ['', 'lowest']
    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug
          coverage: xdebug
        env:
          update: true

      # —— Composer️ —————————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.composer-dependencies }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.composer-dependencies }}-

      - name: Install Composer dependencies
        if: matrix.composer-dependencies == ''
        run: composer update --no-suggest

      - name: Install Composer dependencies - Lowest
        if: matrix.composer-dependencies == 'lowest'
        run: composer update --no-suggest --prefer-lowest

      # —— Style —————————————————————————————————————————————————————————
      - name: Launch PHP-CS-FIXER - src
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run src

      # —— Style —————————————————————————————————————————————————————————
      - name: Launch PHP-CS-FIXER - tests
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run tests

      # —— PHPUnit —————————————————————————————————————————————————————————
      - name: Launch PHPUnit tests
        run: php vendor/bin/phpunit tests
#
#      # —— Infection —————————————————————————————————————————————————————————
#      - name: Launch Infection analysis
#        run: php vendor/bin/infection
#        continue-on-error: true
